version: '2'

services:

  ckan:
    image: localhost:9992/adbpo-ckan-app
    container_name: adbpo-ckan-container
    environment:
      CKAN_DEBUG: "false"
      CKAN_SITE_URL: http://localhost:5000
      CKAN_ADMIN_EMAIL: ckanadmin@mail.com
      CKAN_ADMIN_USERNAME: ckanadmin
      CKAN_ADMIN_PASSWORD: ckanpassword
      CKAN_DB_HOST: db
      CKAN_DB_PORT: 5432
      CKAN_DB_USER: ckan
      PGPASSWORD: ckan
      CKAN_SQLALCHEMY_URL: postgresql://ckan:ckan@db:5432/
      CKAN_REDIS_HOST: redis
      CKAN_REDIS_PORT: 6379
      CKAN_REDIS_URL: redis://redis:6379/
      CKAN_SOLR_HOST: solr
      CKAN_SOLR_PORT: 8983
      CKAN_SOLR_URL: http://solr:8983/solr/ckan
    stdin_open: true
    tty: true
    ports:
      - 5000:5000/tcp
      - 8000:8000/tcp
    depends_on:
      - db
      - redis
      - solr
    volumes:
      - ckanlog:/var/log/ckan
      - ./ckan/web/ckan-images:/usr/lib/ckan/default/src/ckan/ckan/public/base/images/adbpo-ckan-images

  solr:
    image: italia/ckan-it-solr:2.3.0-1
    container_name: italia-ckan-it-solr
    stdin_open: true
    tty: true
    volumes:
      - solrdb:/opt/solr/server/solr/ckan/data

  redis:
    image: redis:5.0.5
    container_name: italia-ckan-it-redis
    stdin_open: true
    tty: true

  db:
    image: localhost:9992/adbpo-ckan-db-new
    container_name: adbpo-ckan-db
    environment:
      POSTGRES_USER: ckan
      POSTGRES_PASSWORD: ckan
      POSTGRES_DB: ckan
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432/tcp
    stdin_open: true
    tty: true
    volumes:
      - pgsqldb:/var/lib/postgresql/data
      - ./ckan/db/postgres_dumps:/home/postgres_dumps

volumes:
  pgsqldb:
  solrdb:
  ckanlog:
